site:
  name: MartinTechSolutions
  site: 'https://martintechsolutions.fr'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: MartinTechSolutions
    template: '%s — MartinTechSolutions'
  description: "\U0001F680 Développement web, SEO et solutions digitales sur mesure à Lyon."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: MartinTechSolutions
    images:
      - url: '~/assets/images/LogoMTS.svg'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@martintechsolutions'
    site: '@martintechsolutions'
    cardType: summary_large_image

i18n:
  language: fr
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'categorie'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: 'null'

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"